name: Send a telegram message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCKMT8Wn6USyyhU6YzDYgDzQ
    playlist_id:
      - PL2ec2fnWaf1F4TubVXWgCAoyby2fqfRKS
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ tonylu_bot }}
          token: ${{ 6359937870:AAH5YwAteVJvxYOmMKlaSzgv61aVMX_QTTY}}
          message: |
            *${{on.youtube.outputs.title}}*
            
            ${{on.youtube.outputs.description}} ${{on.youtube.outputs.link}}
          format: markdown








